### PR TITLE
Google has deprecated chrome apps in 2018

### PR DESCRIPTION
**Pull request by Sajo8**

### CODE REVIEW

**Comment by TamtamHero** [comment]
I can still install the Ledger Bitcoin chromeapp from the store. I guess it's not totally deprecated yet !

**Comment by Sajo8** [comment]
Fair enough, I don't use Chrome, just opened the PR since it's 2019 now. Shall I close it?

**Comment by Sajo8** [comment]
Or change it to `Google has said it will start deprecating chrome apps 2018 onwards`?

**Comment by Sajo8** [comment]
That's good :+1:

**Pull request merged**
